const fs = require('node:fs');
const path = require('node:path');
const dotenv = require('dotenv');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'apps', 'web', 'src', 'environments', 'environment.ts');

// Load .env.local into process.env (existing process.env values take priority)
dotenv.config({ path: path.join(ROOT, '.env.local') });

function env(key, fallback = '') {
  return (process.env[key] || fallback).trim();
}

const NODE_ENV = env('NODE_ENV', 'development');
const MAINTENANCE_MODE = env('MAINTENANCE_MODE', 'false');
const SUPABASE_URL = env('SUPABASE_URL', 'http://127.0.0.1:54321');
const SUPABASE_ANON_KEY = env('SUPABASE_ANON_KEY');

const str = (v) => `'${v.replace(/'/g, "\\'")}'`;

const content = `// This file is generated by scripts/set-env.js — do not edit manually.
export const environment = {
  production: ${NODE_ENV === 'production'},
  maintenanceMode: ${MAINTENANCE_MODE === 'true'},
  supabaseUrl: ${str(SUPABASE_URL)},
  supabaseAnonKey: ${str(SUPABASE_ANON_KEY)},
};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, content, 'utf-8');
console.log(`[set-env] Generated ${path.relative(ROOT, OUT)} (NODE_ENV=${NODE_ENV})`);
