const fs = require('node:fs');
const path = require('node:path');
const dotenv = require('dotenv');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'apps', 'web', 'src', 'environments', 'environment.ts');

// Load .env.local into process.env (existing process.env values take priority)
dotenv.config({ path: path.join(ROOT, '.env.local') });

const NODE_ENV = process.env.NODE_ENV || 'development';
const MAINTENANCE_MODE = process.env.MAINTENANCE_MODE || 'false';
const SUPABASE_URL = process.env.SUPABASE_URL || 'http://127.0.0.1:54321';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

const content = `// This file is generated by scripts/set-env.js — do not edit manually.
export const environment = {
  production: ${NODE_ENV === 'production'},
  maintenanceMode: ${MAINTENANCE_MODE === 'true'},
  supabaseUrl: '${SUPABASE_URL}',
  supabaseAnonKey: '${SUPABASE_ANON_KEY}',
};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, content, 'utf-8');
console.log(`[set-env] Generated ${path.relative(ROOT, OUT)} (NODE_ENV=${NODE_ENV})`);
